[package]
name = "adhanapp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
home = "0.5"
tokio = { version = "1", features = ["full"] }
rodio = "0.17"
chrono = "0.4.31"
rand = "0.8"
