# Copyright 2022-2024, axodotdev
# SPDX-License-Identifier: MIT or Apache-2.0
#
# CI that:
#
# * checks for a Git Tag that looks like a release
# * builds artifacts with cargo-dist (archives, installers, hashes)
# * uploads those artifacts to temporary workflow zip
# * on success, uploads the artifacts to a GitHub Release
#
# Note that the GitHub Release will be created with a generated
# title/body based on your changelogs.

# Modernized GitHub Actions workflow for multi-platform Rust builds
# Builds and uploads binaries for Linux, Windows, and macOS

name: Release

on:
  push:
    tags:
      - 'v-*'
      - '**[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - armv7-unknown-linux-gnueabihf  # Raspberry Pi (32-bit)
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable
      - name: Install cross-compilation tools (non-armv7 only)
        if: matrix.target != 'armv7-unknown-linux-gnueabihf'
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
      - name: Install system dependencies (native Linux only)
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: sudo apt-get update && sudo apt-get install -y pkg-config libssl-dev libasound2-dev build-essential
      - name: Install system dependencies (armv7 only)
        if: matrix.target == 'armv7-unknown-linux-gnueabihf'
        run: sudo apt-get update && sudo apt-get install -y pkg-config libssl-dev libasound2-dev build-essential
      - name: Build
        run: cargo build --release
      - name: Prepare artifact
        run: |
          mkdir -p dist
          if [[ "${{ matrix.target }}" == *windows* ]]; then
            cp target/${{ matrix.target }}/release/adhanapp.exe dist/adhanapp-${{ matrix.target }}.exe
          else
            cp target/${{ matrix.target }}/release/adhanapp dist/adhanapp-${{ matrix.target }}
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: adhanapp-${{ matrix.target }}
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
